### ISSUE TITLE
WEBDAV publically accessible despite enviroment settings

### ISSUE THREAD

**Issue by kyle-mckay** [loganmarchione/docker-webdav-nginx#18]
Hopefully I'm just being stupid here and missing something, as your solution seems fairly strait forward and simple. I spun up a compose with user, password and file size all defined, only different thing was the volume location mapping to the host that was changed. The issue, is that when I connect to the webdav to test through the browser there is no prompt for authentication and if anyone found out about the URL they could access the files. 

![2023-08-25_14h39_46](https://github.com/loganmarchione/docker-webdav-nginx/assets/83886427/81115f5b-b41d-4eb2-8fb6-80a09ff8d721)

For context if it matters, the host port is being passed through NGINX proxy manager.

my docker compose
``` YML
version: '3'
services:
  webdav:
    container_name: docker-webdav-nginx
    restart: unless-stopped
    environment:
      - WEBDAV_USER=${USER}
      - WEBDAV_PASS=${PASSWORD}
      - NGINX_CLIENT_MAX_BODY_SIZE=${MAX_FILE_SIZE} #ex 500M, 0 for no limit
    networks:
      - webdav
    ports:
      - '8617:80'
    volumes:
      - '/e/userfiles/users/exampleuser:/var/www/webdav'
    image: loganmarchione/docker-webdav-nginx:latest

networks:
  webdav:

#volumes:
#  webdav:
#    driver: local
```

**Comment by loganmarchione** [comment]
What path are you visiting?

/public - No authentication
/restricted - Authentication if specified

**Comment by kyle-mckay** [comment]
Neither. The only path being used is as per your example compose which is `/var/www/webdav`. Based on the Explanation section in the readme I honestly assumed it would dynamically assign the path if authentication variables were defined. Would I just need to update the volume to `/var/www/webdav/restricted`?

**Comment by loganmarchione** [comment]
I mean in the browser?

**Comment by kyle-mckay** [comment]
I was simply putting in https://exampledav.domain.com or equivelent to `localhost:8617`. Using either ./public or ./restricted in the browser path result in a 404.
![image](https://github.com/loganmarchione/docker-webdav-nginx/assets/83886427/f82a92e4-3c0c-44c7-97bb-601e4c3b1c3c)

**Comment by kyle-mckay** [comment]
Saying that, I updated the container path to `/var/www/webdav/restricted` and spun the container back up and now I see the two options and it is prompting for authentication. So by having `${hostpath};/var/www/webdav` it is acting like the public and restricted entry points were overwritten.
![image](https://github.com/loganmarchione/docker-webdav-nginx/assets/83886427/217b0605-bed2-408a-9aaf-5fb36f0b2a25)
Example of the working docker-compose
```YML
version: '3'
services:
  webdav:
    container_name: docker-webdav-nginx
    restart: unless-stopped
    environment:
      - WEBDAV_USER=${USER}
      - WEBDAV_PASS=${PASSWORD}
      - NGINX_CLIENT_MAX_BODY_SIZE=${MAX_FILE_SIZE} #ex 500M or 0 for no limit
    networks:
      - webdav
    ports:
      - '8617:80'
    volumes:
      #- '/e/userfiles/users/kylemckay:/var/www/webdav' #public for some reason
      - '/e/userfiles/users/kylemckay:/var/www/webdav/restricted' #working with authentication
    image: loganmarchione/docker-webdav-nginx:latest

networks:
  webdav:

#volumes:
#  webdav:
#    driver: local
```
